version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hotel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hotel_management
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: hotel_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hotel_user -d hotel_management"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hotel_network

  redis:
    image: redis:7-alpine
    container_name: hotel_redis
    restart: unless-stopped
    command: redis-server --requirepass hotel_redis_password
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hotel_network

networks:
  hotel_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
